### ISSUE TITLE
Crash when attacked by a mob

### ISSUE THREAD

**Issue by Prometheius** [taji34/Troncraft#1]
TronCraft Version:  troncraft-1.7.10-3.0a.jar
Minecraft Version:  1.7.10
Forge Version:      FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291
Java Version:       Java Version: 1.7.0_72, Oracle Corporation  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Bug/Crash Description:  Minecraft crashes sometimes when I attack a hostile mod
Link to pastebin of forge crash log (if game crashed):  http://pastebin.com/8PZdNgDu

Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at com.taji34.troncraft.events.TajiEvents.entityAttacked(TajiEvents.java:63)

**Comment by taji34** [comment]
Does it happen just with hostile mobs or all mobs? Can you give a description of how to repeat the crash?

**Comment by Prometheius** [comment]
I added your mod to FTB Space Astronomy modpack. The crash happened twice so far when I hit a baby zombie and a zombie villager while flying with a jetpack from the Simply Jetpacks mod. After I restarted Minecraft with the baby zombie, it didn't crash when I hit it.

The crashlog for the baby zombie is: http://pastebin.com/D4wQ3gqW

I disabled your mod and spawned a pit of zombies to see if Minecraft still crashes. I was able to kill all of the zombies without crashing.

**Comment by taji34** [comment]
It is this mod causing the crash, I'll work on a bug fix, for now I guess you'll have to keep it disabled, sorry about that.

**Comment by Prometheius** [comment]
I crashed when I took damage: http://pastebin.com/WD3fe1jp

I don't mind the occasional crash.

**Comment by taji34** [comment]
Identified the bug, should be fixed in next update. Issue will stay open until update is released.

**Comment by welnanick** [comment]
Code base restructure, issue no longer relevant.
