### ISSUE TITLE
Crash when trying to make a vanilla crafting table

### ISSUE THREAD

**Issue by Prometheius** [taji34/Troncraft#2]
TronCraft Version: troncraft-1.7.10-3.0a.jar (added into FTB Space Astronomy v1.0.10)
Minecraft Version: 1.7.10
Forge Version: FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291
Java Version: Java Version: 1.7.0_72, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Bug/Crash Description: Minecraft crashed when I tried to create a vanilla crafting table
Link to pastebin of forge crash log (if game crashed):
http://pastebin.com/Nx5FSKQN
http://pastebin.com/dcEaHHig

**Comment by taji34** [comment]
Since you have two crash logs I assume this is repeatable? I'll get on that.

**Comment by taji34** [comment]
Can you provide a reliable way to re-create the crash? I can't seem to get it to crash on my machine.

**Comment by welnanick** [comment]
Code base restructure, issue no longer relevant.
