### ISSUE TITLE
Crash when shot by a skeleton.

### ISSUE THREAD

**Issue by WhoDaPie** [taji34/Troncraft#4]
TronCraft Version: troncraft-1.7.10-3.0a.jar
Minecraft Version: 1.7.10
Forge Version: FML: release 1.7.10-Forge10.13.3.1401-1710ls
Java Version: I'm using the new Mincraft loader thingy, that doesn't use Java.
Bug/Crash Description: Minecraft crashes when I'm shot by a skeleton.
Link to pastebin of forge crash log (if game crashed): I'm sorry, but I'm a noob and idk wha this is.

Sorry, to be a nuisance. I tried your troncraft-1.7.10-2.3a.jar and it works fine, but it doesn't have all your cool new additions/ changes. Please help, if you can. It would be greatly appreciated. :)

**Comment by welnanick** [comment]
Code base restructure, issue no longer relevant.
